/* eslint-disable */
//-------------------------------------------------------------------------------
// Contains all constants used by reducers and actions
//
//
//-------------------------------------------------------------------------------

//-------------------------------------------------------------------------------
// MODIFY STORE WITHOUT MAKING API CALLS
//-------------------------------------------------------------------------------

const CLEAR_ERROR_USER_MESSAGE = 'Company/CLEAR_ERROR_USER_MESSAGE';

const CREATE_SIGNER = 'Company/CREATE_SIGNER';
const UPDATE_SIGNER = 'Company/UPDATE_SIGNER';
const REMOVE_SIGNER = 'Company/REMOVE_SIGNER';
const SAVE_SIGNERS = 'Company/SAVE_SIGNERS';

const CREATE_CONTACT = 'Company/CREATE_CONTACT';
const UPDATE_CONTACT = 'Company/UPDATE_CONTACT';
const REMOVE_CONTACT = 'Company/REMOVE_CONTACT';
const SAVE_CONTACTS = 'Company/SAVE_CONTACT';


//-------------------------------------------------------------------------------
// MODIFY STORE WITH MAKING API CALLS
//-------------------------------------------------------------------------------


const FETCH_DATA = 'Company/FETCH_DATA';
const FETCH_DATA_BEGIN = 'Company/FETCH_DATA_BEGIN';
const FETCH_DATA_QUEUE = 'Company/FETCH_DATA_QUEUE';
const FETCH_DATA_SUCCESS = 'Company/FETCH_DATA_SUCCESS';
const FETCH_DATA_FAILURE = 'Company/FETCH_DATA_FAILURE';



const UPDATE_GENERAL_INFO = 'Company/UPDATE_GENERAL_INFO';
const UPDATE_GENERAL_INFO_BEGIN = 'Company/UPDATE_GENERAL_INFO_BEGIN';
const UPDATE_GENERAL_INFO_QUEUE = 'Company/UPDATE_GENERAL_INFO_QUEUE';
const UPDATE_GENERAL_INFO_SUCCESS = 'Company/UPDATE_GENERAL_INFO_SUCCESS';
const UPDATE_GENERAL_INFO_FAILURE = 'Company/UPDATE_GENERAL_INFO_FAILURE';


const UPDATE_BUSINESS_INFO = 'Company/UPDATE_COMPANY_BUSINESS_INFO';
const UPDATE_BUSINESS_INFO_BEGIN = 'Company/UPDATE_COMPANY_BUSINESS_INFO_BEGIN';
const UPDATE_BUSINESS_INFO_QUEUE = 'Company/UPDATE_COMPANY_BUSINESS_INFO_QUEUE';
const UPDATE_BUSINESS_INFO_SUCCESS = 'Company/UPDATE_COMPANY_BUSINESS_INFO_SUCCESS';
const UPDATE_BUSINESS_INFO_FAILURE = 'Company/UPDATE_COMPANY_BUSINESS_INFO_FAILURE';


const CRUD_SIGNERS = 'Company/CRUD_SIGNERS';
const CRUD_SIGNERS_BEGIN = 'Company/CRUD_SIGNERS_BEGIN';
const CRUD_SIGNERS_QUEUE = 'Company/CRUD_SIGNERS_QUEUE';
const CRUD_SIGNERS_SUCCESS = 'Company/CRUD_SIGNERS_SUCCESS';
const CRUD_SIGNERS_FAILURE = 'Company/CRUD_SIGNERS_FAILURE';


const CRUD_CONTACTS = 'Company/CRUD_CONTACTS';
const CRUD_CONTACTS_BEGIN = 'Company/CRUD_CONTACTS_BEGIN';
const CRUD_CONTACTS_QUEUE = 'Company/CRUD_CONTACTS_QUEUE';
const CRUD_CONTACTS_SUCCESS = 'Company/CRUD_CONTACTS_SUCCESS';
const CRUD_CONTACTS_FAILURE = 'Company/CRUD_CONTACTS_FAILURE';


const UPDATE_ACCOUNTING_SOFTWARE = 'Company/UPDATE_ACCOUNTING_SOFTWARE';
const UPDATE_ACCOUNTING_SOFTWARE_BEGIN = 'Company/UPDATE_ACCOUNTING_SOFTWARE_BEGIN';
const UPDATE_ACCOUNTING_SOFTWARE_QUEUE = 'Company/UPDATE_ACCOUNTING_SOFTWARE_QUEUE';
const UPDATE_ACCOUNTING_SOFTWARE_FAILURE = 'Company/UPDATE_ACCOUNTING_SOFTWARE_FAILURE';
const UPDATE_ACCOUNTING_SOFTWARE_SUCCESS = 'Company/UPDATE_ACCOUNTING_SOFTWARE_SUCCESS';

const SET_SOLE_DIRECTOR = 'Company/SET_SOLE_DIRECTOR';
const SET_SOLE_DIRECTOR_BEGIN = 'Company/SET_SOLE_DIRECTOR_BEGIN';
const SET_SOLE_DIRECTOR_QUEUE = 'Company/SET_SOLE_DIRECTOR_QUEUE';
const SET_SOLE_DIRECTOR_FAILURE = 'Company/SET_SOLE_DIRECTOR_FAILURE';

const SET_USER_AUTHORIZED = 'Company/SET_USER_AUTHORIZED';
const SET_USER_AUTHORIZED_BEGIN = 'Company/SET_USER_AUTHORIZED_BEGIN';
const SET_USER_AUTHORIZED_QUEUE = 'Company/SET_USER_AUTHORIZED_QUEUE';
const SET_USER_AUTHORIZED_FAILURE = 'Company/SET_USER_AUTHORIZED_FAILURE';

const VERIFY_SETUP = 'Company/VERIFY_SETUP';
const VERIFY_SETUP_BEGIN = 'Company/VERIFY_SETUP_BEGIN';
const VERIFY_SETUP_FAILURE = 'Company/VERIFY_SETUP_FAILURE';
const VERIFY_SETUP_SUCCESS = 'Company/VERIFY_SETUP_SUCCESS';


const HAS_DOCS_BEEN_SIGNED_TOGGLE_TRUE = 'Company/HAS_DOCS_BEEN_SIGNED_TOGGLE_TRUE';
const HAS_DOCS_BEEN_SIGNED_TOGGLE_FALSE = 'Company/HAS_DOCS_BEEN_SIGNED_TOGGLE_FALSE';


const REQUEST_CHANGE = 'Company/REQUEST_CHANGE';
const REQUEST_CHANGE_BEGIN = 'Company/REQUEST_CHANGE_BEGIN';
const REQUEST_CHANGE_QUEUE = 'Company/REQUEST_CHANGE_QUEUE';
const REQUEST_CHANGE_SUCCESS = 'Company/REQUEST_CHANGE_SUCCESS';
const REQUEST_CHANGE_FAILURE = 'Company/REQUEST_CHANGE_FAILURE';


const ADD_USER = 'Company/ADD_USER';
const ADD_USER_BEGIN = 'Company/ADD_USER_BEGIN';
const ADD_USER_QUEUE = 'Company/ADD_USER_QUEUE';
const ADD_USER_SUCCESS = 'Company/ADD_USER_SUCCESS';
const ADD_USER_FAILURE = 'Company/ADD_USER_FAILURE';

const ADD_CONTACT = 'Company/ADD_CONTACT';
const ADD_CONTACT_BEGIN = 'Company/ADD_CONTACT_BEGIN';
const ADD_CONTACT_QUEUE = 'Company/ADD_CONTACT_QUEUE';
const ADD_CONTACT_SUCCESS = 'Company/ADD_CONTACT_SUCCESS';
const ADD_CONTACT_FAILURE = 'Company/ADD_CONTACT_FAILURE';

const EDIT_USER = 'Company/EDIT_USER';
const EDIT_USER_BEGIN = 'Company/EDIT_USER_BEGIN';
const EDIT_USER_QUEUE = 'Company/EDIT_USER_QUEUE';
const EDIT_USER_SUCCESS = 'Company/EDIT_USER_SUCCESS';
const EDIT_USER_FAILURE = 'Company/EDIT_USER_FAILURE';

const CHANGE_PROFILE_PICTURE = 'Company/CHANGE_PROFILE_PICTURE';
const CHANGE_PROFILE_PICTURE_BEGIN = 'Company/CHANGE_PROFILE_PICTURE_BEGIN';
const CHANGE_PROFILE_PICTURE_QUEUE = 'Company/CHANGE_PROFILE_PICTURE_QUEUE';
const CHANGE_PROFILE_PICTURE_SUCCESS = 'Company/CHANGE_PROFILE_PICTURE_SUCCESS';
const CHANGE_PROFILE_PICTURE_FAILURE = 'Company/CHANGE_PROFILE_PICTURE_FAILURE';


const ADD_OR_DEACTIVATE_USER_BEGIN = 'ADD_USER_BEGIN';
const ADD_OR_DEACTIVATE_USER_SUCCESS = 'ADD_USER_SUCCESS';
const ADD_OR_DEACTIVATE_USER_FAILURE = 'ADD_USER_FAILURE';

const TOGGLE_ACTIVATION_CONTACT = 'Company/TOGGLE_ACTIVATION_CONTACT';
const TOGGLE_ACTIVATION_CONTACT_BEGIN = 'Company/TOGGLE_ACTIVATION_CONTACT_BEGIN';
const TOGGLE_ACTIVATION_CONTACT_QUEUE = 'Company/TOGGLE_ACTIVATION_CONTACT_QUEUE';
const TOGGLE_ACTIVATION_CONTACT_SUCCESS = 'Company/TOGGLE_ACTIVATION_CONTACT_SUCCESS';
const TOGGLE_ACTIVATION_CONTACT_FAILURE = 'Company/TOGGLE_ACTIVATION_CONTACT_FAILURE';

const TOGGLE_ACTIVATION_USER = 'Company/TOGGLE_ACTIVATION_USER';
const TOGGLE_ACTIVATION_USER_BEGIN = 'Company/TOGGLE_ACTIVATION_USER_BEGIN';
const TOGGLE_ACTIVATION_USER_QUEUE = 'Company/TOGGLE_ACTIVATION_USER_QUEUE';
const TOGGLE_ACTIVATION_USER_SUCCESS = 'Company/TOGGLE_ACTIVATION_USER_SUCCESS';
const TOGGLE_ACTIVATION_USER_FAILURE = 'Company/TOGGLE_ACTIVATION_USER_FAILURE';

const SET_DEFAULT_CURRENCY = 'Company/SET_DEFAULT_CURRENCY';
const SET_DEFAULT_CURRENCY_BEGIN = 'Company/SET_DEFAULT_CURRENCY_BEGIN';
const SET_DEFAULT_CURRENCY_QUEUE = 'Company/SET_DEFAULT_CURRENCY_QUEUE';
const SET_DEFAULT_CURRENCY_SUCCESS = 'Company/SET_DEFAULT_CURRENCY_SUCCESS';
const SET_DEFAULT_CURRENCY_FAILURE = 'Company/SET_DEFAULT_CURRENCY_FAILURE';

const SET_DEFAULT_LANGUAGE = 'Company/SET_DEFAULT_LANGUAGE';
const SET_DEFAULT_LANGUAGE_BEGIN = 'Company/SET_DEFAULT_LANGUAGE_BEGIN';
const SET_DEFAULT_LANGUAGE_QUEUE = 'Company/SET_DEFAULT_LANGUAGE_QUEUE';
const SET_DEFAULT_LANGUAGE_SUCCESS = 'Company/SET_DEFAULT_LANGUAGE_SUCCESS';
const SET_DEFAULT_LANGUAGE_FAILURE = 'Company/SET_DEFAULT_LANGUAGE_FAILURE';


const SET_DEFAULT_TIMEZONE = 'Company/SET_DEFAULT_TIMEZONE';
const SET_DEFAULT_TIMEZONE_BEGIN = 'Company/SET_DEFAULT_TIMEZONE_BEGIN';
const SET_DEFAULT_TIMEZONE_QUEUE = 'Company/SET_DEFAULT_TIMEZONE_QUEUE';
const SET_DEFAULT_TIMEZONE_SUCCESS = 'Company/SET_DEFAULT_TIMEZONE_SUCCESS';
const SET_DEFAULT_TIMEZONE_FAILURE = 'Company/SET_DEFAULT_TIMEZONE_FAILURE';

const TOGGLE_ALWAYS_PAY_ME_EARLY_ON = 'Company/TOGGLE_ALWAYS_PAY_ME_EARLY_ON';

const TOGGLE_ALWAYS_PAY_ME_EARLY = 'Company/TOGGLE_ALWAYS_PAY_ME_EARLY';
const TOGGLE_ALWAYS_PAY_ME_EARLY_BEGIN = 'Company/TOGGLE_ALWAYS_PAY_ME_EARLY_BEGIN';
const TOGGLE_ALWAYS_PAY_ME_EARLY_QUEUE = 'Company/TOGGLE_ALWAYS_PAY_ME_EARLY_QUEUE';
const TOGGLE_ALWAYS_PAY_ME_EARLY_SUCCESS = 'Company/TOGGLE_ALWAYS_PAY_ME_EARLY_SUCCESS';
const TOGGLE_ALWAYS_PAY_ME_EARLY_FAILURE = 'Company/TOGGLE_ALWAYS_PAY_ME_EARLY_FAILURE';

const UPDATE_ALWAYS_PAY_ME_EARLY = 'Company/UPDATE_ALWAYS_PAY_ME_EARLY';
const UPDATE_ALWAYS_PAY_ME_EARLY_BEGIN = 'Company/UPDATE_ALWAYS_PAY_ME_EARLY_BEGIN';
const UPDATE_ALWAYS_PAY_ME_EARLY_QUEUE = 'Company/UPDATE_ALWAYS_PAY_ME_EARLY_QUEUE';
const UPDATE_ALWAYS_PAY_ME_EARLY_SUCCESS = 'Company/UPDATE_ALWAYS_PAY_ME_EARLY_SUCCESS';
const UPDATE_ALWAYS_PAY_ME_EARLY_FAILURE = 'Company/UPDATE_ALWAYS_PAY_ME_EARLY_FAILURE';

const CHANGE_CURRENT_CUSTOMER = 'Company/CHANGE_CURRENT_CUSTOMER';

const CANCEL_SIGNATURE = 'Company/CANCEL_SIGNATURE';

export default {

  TOGGLE_ACTIVATION_CONTACT,
  TOGGLE_ACTIVATION_CONTACT_BEGIN,
  TOGGLE_ACTIVATION_CONTACT_QUEUE,
  TOGGLE_ACTIVATION_CONTACT_SUCCESS,
  TOGGLE_ACTIVATION_CONTACT_FAILURE,

  TOGGLE_ACTIVATION_USER,
  TOGGLE_ACTIVATION_USER_BEGIN,
  TOGGLE_ACTIVATION_USER_QUEUE,
  TOGGLE_ACTIVATION_USER_SUCCESS,
  TOGGLE_ACTIVATION_USER_FAILURE,

  CREATE_SIGNER,
  REMOVE_SIGNER,
  UPDATE_SIGNER,
  SAVE_SIGNERS,

  CREATE_CONTACT,
  REMOVE_CONTACT,
  UPDATE_CONTACT,
  SAVE_CONTACTS,

  FETCH_DATA,
  FETCH_DATA_BEGIN,
  FETCH_DATA_QUEUE,
  FETCH_DATA_SUCCESS,
  FETCH_DATA_FAILURE,

  UPDATE_GENERAL_INFO,
  UPDATE_GENERAL_INFO_BEGIN,
  UPDATE_GENERAL_INFO_QUEUE,
  UPDATE_GENERAL_INFO_SUCCESS,
  UPDATE_GENERAL_INFO_FAILURE,

  UPDATE_BUSINESS_INFO,
  UPDATE_BUSINESS_INFO_BEGIN,
  UPDATE_BUSINESS_INFO_QUEUE,
  UPDATE_BUSINESS_INFO_SUCCESS,
  UPDATE_BUSINESS_INFO_FAILURE,

  CRUD_SIGNERS,
  CRUD_SIGNERS_BEGIN,
  CRUD_SIGNERS_QUEUE,
  CRUD_SIGNERS_SUCCESS,
  CRUD_SIGNERS_FAILURE,

  CRUD_CONTACTS,
  CRUD_CONTACTS_BEGIN,
  CRUD_CONTACTS_QUEUE,
  CRUD_CONTACTS_SUCCESS,
  CRUD_CONTACTS_FAILURE,

  UPDATE_ACCOUNTING_SOFTWARE,
  UPDATE_ACCOUNTING_SOFTWARE_BEGIN,
  UPDATE_ACCOUNTING_SOFTWARE_QUEUE,
  UPDATE_ACCOUNTING_SOFTWARE_FAILURE,
  UPDATE_ACCOUNTING_SOFTWARE_SUCCESS,

  SET_SOLE_DIRECTOR,
  SET_SOLE_DIRECTOR_BEGIN,
  SET_SOLE_DIRECTOR_QUEUE,
  SET_SOLE_DIRECTOR_FAILURE,

  SET_USER_AUTHORIZED,
  SET_USER_AUTHORIZED_BEGIN,
  SET_USER_AUTHORIZED_QUEUE,
  SET_USER_AUTHORIZED_FAILURE,

  VERIFY_SETUP,
  VERIFY_SETUP_BEGIN,
  VERIFY_SETUP_FAILURE,
  VERIFY_SETUP_SUCCESS,

  HAS_DOCS_BEEN_SIGNED_TOGGLE_TRUE,
  HAS_DOCS_BEEN_SIGNED_TOGGLE_FALSE,

  REQUEST_CHANGE,
  REQUEST_CHANGE_BEGIN,
  REQUEST_CHANGE_QUEUE,
  REQUEST_CHANGE_SUCCESS,
  REQUEST_CHANGE_FAILURE,

  ADD_USER,
  ADD_USER_BEGIN,
  ADD_USER_QUEUE,
  ADD_USER_SUCCESS,
  ADD_USER_FAILURE,

  ADD_CONTACT,
  ADD_CONTACT_BEGIN,
  ADD_CONTACT_QUEUE,
  ADD_CONTACT_SUCCESS,
  ADD_CONTACT_FAILURE,

  EDIT_USER,
  EDIT_USER_BEGIN,
  EDIT_USER_QUEUE,
  EDIT_USER_SUCCESS,
  EDIT_USER_FAILURE,

  SET_DEFAULT_CURRENCY,
  SET_DEFAULT_CURRENCY_BEGIN,
  SET_DEFAULT_CURRENCY_QUEUE,
  SET_DEFAULT_CURRENCY_SUCCESS,
  SET_DEFAULT_CURRENCY_FAILURE,

  SET_DEFAULT_LANGUAGE,
  SET_DEFAULT_LANGUAGE_BEGIN,
  SET_DEFAULT_LANGUAGE_QUEUE,
  SET_DEFAULT_LANGUAGE_SUCCESS,
  SET_DEFAULT_LANGUAGE_FAILURE,

  SET_DEFAULT_TIMEZONE,
  SET_DEFAULT_TIMEZONE_BEGIN,
  SET_DEFAULT_TIMEZONE_QUEUE,
  SET_DEFAULT_TIMEZONE_SUCCESS,
  SET_DEFAULT_TIMEZONE_FAILURE,

  CLEAR_ERROR_USER_MESSAGE,
  ADD_OR_DEACTIVATE_USER_BEGIN,
  ADD_OR_DEACTIVATE_USER_SUCCESS,
  ADD_OR_DEACTIVATE_USER_FAILURE,

  CHANGE_PROFILE_PICTURE,
  CHANGE_PROFILE_PICTURE_BEGIN,
  CHANGE_PROFILE_PICTURE_QUEUE,
  CHANGE_PROFILE_PICTURE_SUCCESS,
  CHANGE_PROFILE_PICTURE_FAILURE,

  TOGGLE_ALWAYS_PAY_ME_EARLY,
  TOGGLE_ALWAYS_PAY_ME_EARLY_BEGIN,
  TOGGLE_ALWAYS_PAY_ME_EARLY_QUEUE,
  TOGGLE_ALWAYS_PAY_ME_EARLY_SUCCESS,
  TOGGLE_ALWAYS_PAY_ME_EARLY_FAILURE,

  UPDATE_ALWAYS_PAY_ME_EARLY,
  UPDATE_ALWAYS_PAY_ME_EARLY_BEGIN,
  UPDATE_ALWAYS_PAY_ME_EARLY_QUEUE,
  UPDATE_ALWAYS_PAY_ME_EARLY_SUCCESS,
  UPDATE_ALWAYS_PAY_ME_EARLY_FAILURE,

  TOGGLE_ALWAYS_PAY_ME_EARLY_ON,

  CHANGE_CURRENT_CUSTOMER,

  CANCEL_SIGNATURE,
};

